### ISSUE TITLE
Unable to install due to OS/LV issue

### ISSUE THREAD

**Issue by wegunterjr-Dematic** [filipealtoe/LabVIEWforRasPiVIPM#1]
Trying to install:  tsxperts_spw_lib_raspberry_pi_compiler_for_labview Beta 1 LV2015

This package is not compatible with your operating system or any Labview version installed on your..

I am running windows 7, LV 2015.

**Comment by maristu** [comment]
I have similar issue. 

I am runnig windows 7, LV 2013 SP2. It' is possible to recompile the file *.vip into LV 2013?

If it's not, in a few day I will receive LV 2015 SP2 and I will continue with the test.

**Comment by filipealtoe** [comment]
No; unfortunately; the compiler only supports LV 2014 and above. 

Thanks
Filipe

**Comment by wegunterjr-Dematic** [comment]
@filipealtoe  I am running Windows 7 and LabVIEW 2015, but getting the errors show above in my original post. What do you suggest?

**Comment by labviewforRaspi** [comment]
@wegunterjr-Dematic - I have sent an e-mail to the Beta Tester e-mail distribution list this past weekend about this very issue. You need to download the files via clicking the Download Zip button and not by right clicking at the file and doing a Save As.

**Comment by wegunterjr-Dematic** [comment]
ah, totally spaced that.  I saw it in passing, but didn't act on it at the time. Thanks.  Back at it later today...

**Comment by wegunterjr-Dematic** [comment]
I thought I downloaded them, but I did it the wrong way (i did a right click first). this time, I downloaded using the Download Zip button, and am all installed.  Thanks!
